sampleNames:
  - SRR17287624
  - SRR17287623
  - SRR17287622
  - SRR17287630
  - SRR17287625
  - SRR17287627
  - SRR17287620
  - SRR17287628
  - SRR17287629
  - SRR17287621
  - SRR17287626
  - SRR17287615
  - SRR17287614
  - SRR17287619
  - SRR17287616
  - SRR17287617
  - SRR17287618

projectName: "dyeatom_inc"

# megahit configs
megahitMemory: "0.5" # fraction of machine's total memory to set as max limit
megahitThreads: "4" # number of CPU threads

#fraggenescan
error: "illumina_1" # Illumina sequencing reads with about 0.1% error rate
fgsThreads: "4" # number of threads to use

# Salmon configs 
salmonThreads: 4 # Integer rather than string input required. 8 — 12 threads is recommended for optimal performance.